language: go

go:
  - 1.8.3

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
  - mkdir -p dist
  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o ./dist/gomotics
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=$DOCKER_USER/kronincloud
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
  - echo $REPO:$TAG
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO